# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew. DO NOT EDIT.
class Workflow < Formula
  desc "Workflow CLI tool for PR management, Jira integration, and log processing"
  homepage "https://github.com/zevwings/workflow.rs"
  version "master-v0.0.1"
  license "MIT"

  # 方式一：从源码构建（推荐用于开发阶段）
  # 如果有 GitHub Releases，可以使用方式二
  depends_on "rust" => :build

  on_macos do
    # 从源码构建
    url "https://github.com/zevwings/workflow.rs.git", branch: "master"

    # 如果使用 GitHub Releases，可以这样配置：
    # if Hardware::CPU.intel?
    #   url "https://github.com/zevwings/workflow.rs/releases/download/vmaster-v0.0.1/workflow-master-v0.0.1-x86_64-apple-darwin.tar.gz"
    #   sha256 "53f0f764f258ccf3f211353ad430c99602fe5421e8e480fa7e4ab9e7944f4353"
    # end
    # if Hardware::CPU.arm?
    #   url "https://github.com/zevwings/workflow.rs/releases/download/vmaster-v0.0.1/workflow-master-v0.0.1-aarch64-apple-darwin.tar.gz"
    #   sha256 "a17883b5a83509539c595ceec9a3441b51b77a927e3dc5dec7e5912de6fda322"
    # end
  end

  def install
    # 构建所有二进制文件（包括 install，虽然它不会被安装到系统）
    system "cargo", "build", "--release", "--bin", "workflow", "--bin", "pr", "--bin", "qk", "--bin", "install"
    # 只安装用户可用的命令到系统
    bin.install "target/release/workflow"
    bin.install "target/release/pr"
    bin.install "target/release/qk"
    # 注意：install 二进制不安装到系统，它仅用于 shell completion 安装（Makefile 使用）
  end

  def post_install
    # 创建符号链接到 /usr/local/bin（如果目录存在且可写）
    local_bin = "/usr/local/bin"
    homebrew_prefix = ENV.fetch("HOMEBREW_PREFIX", "/opt/homebrew")
    if Dir.exist?(local_bin) && File.writable?(local_bin)
      %w[workflow pr qk].each do |cmd|
        source = "#{homebrew_prefix}/bin/#{cmd}"
        target = "#{local_bin}/#{cmd}"
        if File.exist?(source)
          begin
            FileUtils.ln_sf(source, target)
            ohai "Created symlink: #{target} -> #{source}"
          rescue => e
            opoo "Failed to create symlink #{target}: #{e.message}"
            opoo "You may need to run manually: sudo ln -sf #{source} #{target}"
          end
        end
      end
    else
      opoo "/usr/local/bin is not writable. Creating symlinks requires sudo:"
      opoo "  sudo ln -sf #{homebrew_prefix}/bin/workflow /usr/local/bin/workflow"
      opoo "  sudo ln -sf #{homebrew_prefix}/bin/pr /usr/local/bin/pr"
      opoo "  sudo ln -sf #{homebrew_prefix}/bin/qk /usr/local/bin/qk"
    end
  end

  test do
    system "#{bin}/workflow", "--help"
    system "#{bin}/pr", "--help"
    system "#{bin}/qk", "--help"
  end
end

