# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew. DO NOT EDIT.
class Workflow < Formula
  desc "Workflow CLI tool for PR management, Jira integration, and log processing"
  homepage "https://github.com/zevwings/workflow.rs"
  version "0.0.5"
  license "MIT"

  # 方式一：从源码构建（推荐用于开发阶段）
  # 如果有 GitHub Releases，可以使用方式二
  depends_on "rust" => :build

  on_macos do
    # 从源码构建
    url "https://github.com/zevwings/workflow.rs.git", tag: "v0.0.5"

    # 如果使用 GitHub Releases，可以这样配置：
    # if Hardware::CPU.intel?
    #   url "https://github.com/zevwings/workflow.rs/releases/download/v0.0.1/workflow-0.0.1-x86_64-apple-darwin.tar.gz"
    #   sha256 "dfbb1bde2115321f1a178454fd066e99b9e5489317a3e7677a7208f519293d2e"
    # end
    # if Hardware::CPU.arm?
    #   url "https://github.com/zevwings/workflow.rs/releases/download/v0.0.1/workflow-0.0.1-aarch64-apple-darwin.tar.gz"
    #   sha256 "ed825955eebcd9b5dfd8468956697a972f6781da18a5bae2c33ef519d48aecc8"
    # end
  end

  def install
    # 构建所有二进制文件（包括 install，虽然它不会被安装到系统）
    system "cargo", "build", "--release", "--bin", "workflow", "--bin", "pr", "--bin", "qk", "--bin", "install"
    # 只安装用户可用的命令到系统
    bin.install "target/release/workflow"
    bin.install "target/release/pr"
    bin.install "target/release/qk"

    # 安装 install 二进制文件，用于 post_install 中的 completion 安装
    bin.install "target/release/install"
    # 注意：install 二进制不安装到系统，它仅用于 shell completion 安装（Makefile 使用）
  end

  def post_install
    # 创建符号链接到 /usr/local/bin（如果目录存在且可写）
    local_bin = "/usr/local/bin"
    homebrew_prefix = ENV.fetch("HOMEBREW_PREFIX", "/opt/homebrew")
    if Dir.exist?(local_bin) && File.writable?(local_bin)
      %w[workflow pr qk].each do |cmd|
        source = "#{homebrew_prefix}/bin/#{cmd}"
        target = "#{local_bin}/#{cmd}"
        if File.exist?(source)
          begin
            FileUtils.ln_sf(source, target)
            ohai "Created symlink: #{target} -> #{source}"
          rescue => e
            opoo "Failed to create symlink #{target}: #{e.message}"
            opoo "You may need to run manually: sudo ln -sf #{source} #{target}"
          end
        end
      end
    else
      opoo "/usr/local/bin is not writable. Creating symlinks requires sudo:"
      opoo "  sudo ln -sf #{homebrew_prefix}/bin/workflow /usr/local/bin/workflow"
      opoo "  sudo ln -sf #{homebrew_prefix}/bin/pr /usr/local/bin/pr"
      opoo "  sudo ln -sf #{homebrew_prefix}/bin/qk /usr/local/bin/qk"
    end
  end

    # 自动安装 shell completion
    # 使用已安装的 install 二进制文件来安装 completions
    install_binary = bin/"install"

    if install_binary.exist? && install_binary.executable?
      home_dir = ENV.fetch("HOME", Dir.home)
      shell_env = ENV.fetch("SHELL", "/bin/zsh")
      ohai "Installing shell completions..."
      ohai "Using HOME: #{home_dir}"
      ohai "Using SHELL: #{shell_env}"
      result = system(install_binary.to_s)
      if result
        ohai "Shell completions installed successfully"
        ohai "To activate completions, run: source ~/.zshrc  # or ~/.bashrc"
      else
        exit_code = $?.exitstatus || 1
        opoo "Failed to install shell completions (exit code: #{exit_code})"
        opoo "You can manually install completions by running:"
        opoo "  #{bin}/install"
        opoo "Or use the workflow command:"
        opoo "  workflow install"
      end
    else
      opoo "Install binary not found at #{install_binary}"
      opoo "Skipping automatic completion installation"
      opoo "You can manually install completions later by running:"
      opoo "  workflow install"
    end

  test do
    system "#{bin}/workflow", "--help"
    system "#{bin}/pr", "--help"
    system "#{bin}/qk", "--help"
  end
end

